version: "3"
services:
  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 8888:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root # 設置 root 密碼
      MYSQL_DATABASE: taravel_docker # 設置數據庫名稱
      MYSQL_USER: custom_user # 設置普通用戶名稱
      MYSQL_PASSWORD: custom_pass # 設置普通用戶密碼
    ports:
      - 3309:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql_db
